apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: scaling
    name: scaling
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: scaling
    strategy: {}
    template:
      metadata:
        labels:
          app: scaling
      spec:
        containers:
        - image: nakanakau/scaling:latest
          name: scaling

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: scaling
    name: scaling
  spec:
    type: NodePort
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: scaling
kind: List
metadata: {}
